CREATE TABLE [dbo].[LastTicketNumber](
	[ticketNumber] [decimal](8, 0) NOT NULL,
 CONSTRAINT [PK_LastTicketNumber] PRIMARY KEY CLUSTERED 
(
	[ticketNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]