
USE [master]
GO

/****** Object:  Database [COMMMSG]    Script Date: 31/03/2020 12:19:24 ******/
CREATE DATABASE [COMMMSG]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'COMMMSG', FILENAME = N'D:\MDF\COMMMSG.mdf' , SIZE = 2457600KB , MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'COMMMSG_log', FILENAME = N'D:\LDF\COMMMSG_log.ldf' , SIZE = 2826240KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [COMMMSG].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [COMMMSG] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [COMMMSG] SET ANSI_NULLS OFF
GO

ALTER DATABASE [COMMMSG] SET ANSI_PADDING OFF
GO

ALTER DATABASE [COMMMSG] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [COMMMSG] SET ARITHABORT OFF
GO

ALTER DATABASE [COMMMSG] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [COMMMSG] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [COMMMSG] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [COMMMSG] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [COMMMSG] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [COMMMSG] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [COMMMSG] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [COMMMSG] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [COMMMSG] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [COMMMSG] SET  DISABLE_BROKER
GO

ALTER DATABASE [COMMMSG] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [COMMMSG] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [COMMMSG] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [COMMMSG] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [COMMMSG] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [COMMMSG] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [COMMMSG] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [COMMMSG] SET RECOVERY SIMPLE
GO

ALTER DATABASE [COMMMSG] SET  MULTI_USER
GO

ALTER DATABASE [COMMMSG] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [COMMMSG] SET DB_CHAINING OFF
GO

ALTER DATABASE [COMMMSG] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [COMMMSG] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [COMMMSG] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [COMMMSG] SET QUERY_STORE = OFF
GO

USE [COMMMSG]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [COMMMSG] SET  READ_WRITE
GO
