
USE [master]
GO

/****** Object:  Database [COMMSCS]    Script Date: 31/03/2020 12:20:33 ******/
CREATE DATABASE [COMMSCS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'COMMSCS', FILENAME = N'D:\MDF\COMMSCS.mdf' , SIZE = 102400KB , MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'COMMSCS_log', FILENAME = N'D:\LDF\COMMSCS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [COMMSCS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [COMMSCS] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [COMMSCS] SET ANSI_NULLS OFF
GO

ALTER DATABASE [COMMSCS] SET ANSI_PADDING OFF
GO

ALTER DATABASE [COMMSCS] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [COMMSCS] SET ARITHABORT OFF
GO

ALTER DATABASE [COMMSCS] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [COMMSCS] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [COMMSCS] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [COMMSCS] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [COMMSCS] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [COMMSCS] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [COMMSCS] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [COMMSCS] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [COMMSCS] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [COMMSCS] SET  DISABLE_BROKER
GO

ALTER DATABASE [COMMSCS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [COMMSCS] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [COMMSCS] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [COMMSCS] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [COMMSCS] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [COMMSCS] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [COMMSCS] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [COMMSCS] SET RECOVERY SIMPLE
GO

ALTER DATABASE [COMMSCS] SET  MULTI_USER
GO

ALTER DATABASE [COMMSCS] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [COMMSCS] SET DB_CHAINING OFF
GO

ALTER DATABASE [COMMSCS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [COMMSCS] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [COMMSCS] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [COMMSCS] SET QUERY_STORE = OFF
GO

USE [COMMSCS]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [COMMSCS] SET  READ_WRITE
GO
