
USE [master]
GO

/****** Object:  Database [COMMPROD]    Script Date: 31/03/2020 12:20:06 ******/
CREATE DATABASE [COMMPROD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'COMMPROD', FILENAME = N'D:\MDF\COMMPROD.mdf' , SIZE = 102400KB , MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'COMMPROD_log', FILENAME = N'D:\LDF\COMMPROD_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [COMMPROD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [COMMPROD] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [COMMPROD] SET ANSI_NULLS OFF
GO

ALTER DATABASE [COMMPROD] SET ANSI_PADDING OFF
GO

ALTER DATABASE [COMMPROD] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [COMMPROD] SET ARITHABORT OFF
GO

ALTER DATABASE [COMMPROD] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [COMMPROD] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [COMMPROD] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [COMMPROD] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [COMMPROD] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [COMMPROD] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [COMMPROD] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [COMMPROD] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [COMMPROD] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [COMMPROD] SET  DISABLE_BROKER
GO

ALTER DATABASE [COMMPROD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [COMMPROD] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [COMMPROD] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [COMMPROD] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [COMMPROD] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [COMMPROD] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [COMMPROD] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [COMMPROD] SET RECOVERY SIMPLE
GO

ALTER DATABASE [COMMPROD] SET  MULTI_USER
GO

ALTER DATABASE [COMMPROD] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [COMMPROD] SET DB_CHAINING OFF
GO

ALTER DATABASE [COMMPROD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [COMMPROD] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [COMMPROD] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [COMMPROD] SET QUERY_STORE = OFF
GO

USE [COMMPROD]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [COMMPROD] SET  READ_WRITE
GO
